{"name": "test_raises", "status": "broken", "statusDetails": {"message": "NameError: name 'connect' is not defined", "trace": "def test_raises():\n        with pytest.raises(TypeError) as e:\n>           connect('localhost', '6379')\nE           NameError: name 'connect' is not defined\n\ntest_raises.py:6: NameError"}, "attachments": [{"name": "stdout", "source": "5242f372-97ad-4358-bc95-a93ff0b88047-attachment.txt", "type": "text/plain"}], "start": 1658814553556, "stop": 1658814553557, "uuid": "981882a3-f683-4462-af9a-341f80ae716c", "historyId": "2041d43c6138909ed4ffdd39e92389f1", "testCaseId": "ff7cfa1bd85f0a8be1a641c08ede084f", "fullName": "test_raises#test_raises", "labels": [{"name": "suite", "value": "test_raises"}, {"name": "host", "value": "k1"}, {"name": "thread", "value": "6313-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_raises"}]}